export const cart = {
  EN: {
    cart: "CART",
    cartEmpty: "Your cart is empty",
    subtotal: "Subtotal",
    deliveryFee: "Delivery Fee",
    deliveryFeeHint: "Calculated automatically from your city",
    freeShipping: "FREE",
    promoCode: "Promo Code",
    promoPlaceholder: "Enter code",
    promoApply: "Apply",
    promoRemove: "Remove",
    promoInvalid: "Invalid or expired code",
    promoDiscount: "Discount",
    total: "Total",
    checkout: "Checkout",
    orderWhatsApp: "Order via WhatsApp",
  },
  FR: {
    cart: "PANIER",
    cartEmpty: "Votre panier est vide",
    subtotal: "Sous-total",
    deliveryFee: "Frais de livraison",
    deliveryFeeHint: "Calculés automatiquement selon votre ville",
    freeShipping: "GRATUITE",
    promoCode: "Code de promotion",
    promoPlaceholder: "Entrer le code",
    promoApply: "Appliquer",
    promoRemove: "Retirer",
    promoInvalid: "Code invalide ou expiré",
    promoDiscount: "Réduction",
    total: "Total",
    checkout: "Commander",
    orderWhatsApp: "Commander via WhatsApp",
  },
} as const;
