export const checkout = {
  EN: {
    confirmOrder: "Confirm Order",
    placing: "Placing...",
    cashOnly: "Cash on delivery only",
    fullName: "Full Name",
    phoneWhatsApp: "Phone (WhatsApp)",
    email: "Email",
    address: "Address",
    city: "City",
    selectCity: "Type to search your city",
    noCityMatch: "No matching city",
    payment: "Payment",
    paymentInfo1: "PAYMENT: Cash on Delivery.",
    paymentInfo2: "No upfront payment is needed. Our delivery partner will send you a",
    paymentInfo3: "WhatsApp text on the day of delivery",
    paymentInfo4: ". Please ensure your phone number is correct.",
    orderReceived: "ORDER RECEIVED",
    continueBtn: "Continue",
    orderPlacedToast: "Order recorded",
    orderErrorToast: "Could not record order. Please try again.",
  },
  FR: {
    confirmOrder: "Confirmer la commande",
    placing: "Envoi...",
    cashOnly: "Paiement à la livraison uniquement",
    fullName: "Nom complet",
    phoneWhatsApp: "Téléphone (WhatsApp)",
    email: "Email",
    address: "Adresse",
    city: "Ville",
    selectCity: "Tapez pour rechercher votre ville",
    noCityMatch: "Aucune ville correspondante",
    payment: "Paiement",
    paymentInfo1: "PAIEMENT : à la livraison.",
    paymentInfo2: "Aucun paiement à l'avance. Notre livreur vous enverra un",
    paymentInfo3: "message WhatsApp le jour de la livraison",
    paymentInfo4: ". Vérifiez bien votre numéro.",
    orderReceived: "COMMANDE REÇUE",
    continueBtn: "Continuer",
    orderPlacedToast: "Commande enregistrée",
    orderErrorToast: "Impossible d'enregistrer la commande. Réessayez.",
  },
} as const;
