export const home = {
  EN: {
    enterIndex: "Enter Index",
    storeTagline: "Garments documented, classified, ready for retrieval.",
    store: "STORE",
    drop001: "Documented Entries",
    drop000: "Passive Memory",
    arrowNew: "↓ Record",
    arrowArchive: "↓ Archive",
    incoming: "IPSEITY — INCOMING",
    systemStatus: "SYSTEM STATUS: INCOMING DROP",
    days: "DAYS",
    hrs: "HRS",
    min: "MIN",
    sec: "SEC",
    markCalendar: "Drop date recorded.",
    storeEN: "This is the store.",
    comingSoon: "Status: Pending",
    initializingSystem: "Initializing System",
  },
  FR: {
    enterIndex: "Entrer dans l'Index",
    storeTagline: "Pièces documentées, classifiées, prêtes à être consultées.",
    store: "BOUTIQUE",
    drop001: "Entrées Documentées",
    drop000: "Mémoire passive",
    arrowNew: "↓ Record",
    arrowArchive: "↓ Archive",
    incoming: "IPSEITY — À VENIR",
    systemStatus: "STATUT : DROP À VENIR",
    days: "JOURS",
    hrs: "HRS",
    min: "MIN",
    sec: "SEC",
    markCalendar: "Drop date recorded.",
    storeEN: "This is the store.",
    comingSoon: "Statut : En attente",
    initializingSystem: "Initialisation du système",
  },
} as const;
