export const product = {
  EN: {
    addToCart: "Add to Cart",
    askWhatsApp: "Ask via WhatsApp",
    soldOut: "Sold Out",
    fewLeft: "Low Stock",
    new: "New",
    selectSize: "Select Size",
    selectColor: "Select Color",
    back: "Back",
    viewAll: "View all",
    loading: "Loading inventory...",
    loadingProduct: "Loading product...",
    inStock: "in stock",
    noProducts: "No products in this category yet.",
    productNotFound: "Product not found",
    backToShop: "Back to shop",
    openArchive: "Open Archive",
    relatedEntries: "Related Entries",
  },
  FR: {
    addToCart: "Ajouter au panier",
    askWhatsApp: "Demander via WhatsApp",
    soldOut: "Épuisé",
    fewLeft: "Presque épuisé",
    new: "Nouveau",
    selectSize: "Choisir la taille",
    selectColor: "Choisir la couleur",
    back: "Retour",
    viewAll: "Voir tout",
    loading: "Chargement...",
    loadingProduct: "Chargement du produit...",
    inStock: "en stock",
    noProducts: "Aucun produit dans cette catégorie.",
    productNotFound: "Produit introuvable",
    backToShop: "Retour à la boutique",
    openArchive: "Ouvrir l'Archive",
    relatedEntries: "Entrées liées",
  },
} as const;
