-- Same problem as unit_price/subtotal (see 20260713020000), one step
-- removed: shipping_fee is computed client-side in src/lib/shipping.ts
-- from a per-city rate table that only ever existed in the frontend, then
-- sent straight to the orders insert with no server-side check at all.
--
-- This mirrors that rate table into Postgres and overwrites shipping_fee
-- from it (by customer_city) the moment an order is inserted, using the
-- same two-tier lookup as the frontend: exact normalized city match first,
-- then a "base name" match (drops parenthetical/region qualifiers, e.g.
-- "Afsou ( nador )" -> "afsou"), falling back to the standard default fee
-- if nothing matches. normalized_city/base_city are precomputed here in
-- the same way src/lib/shipping.ts's normalize()/baseName() do, so the two
-- stay in lockstep; if the rate table or that normalization logic ever
-- changes, both sides need updating together.

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;

CREATE TABLE public.shipping_rates (
  id serial PRIMARY KEY,
  city text NOT NULL,
  fee numeric(10,2) NOT NULL CHECK (fee >= 0),
  normalized_city text NOT NULL,
  base_city text NOT NULL
);

-- Lookups happen by normalized_city / base_city (see functions below);
-- these indexes keep the trigger on every order insert cheap. Not UNIQUE:
-- the source rate sheet has legitimate duplicate/overlapping labels, and
-- "first occurrence wins" (id ASC) reproduces the frontend's Map behavior.
CREATE INDEX shipping_rates_normalized_city_idx ON public.shipping_rates (normalized_city, id);
CREATE INDEX shipping_rates_base_city_idx ON public.shipping_rates (base_city, id);

ALTER TABLE public.shipping_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone reads shipping rates" ON public.shipping_rates FOR SELECT USING (true);

INSERT INTO public.shipping_rates (city, fee, normalized_city, base_city) VALUES
  ('Achakkar', 45, 'achakkar', 'achakkar'),
  ('Afourar', 39, 'afourar', 'afourar'),
  ('Afra', 39, 'afra', 'afra'),
  ('Afsou ( nador )', 45, 'afsou', 'afsou'),
  ('Agadir', 35, 'agadir', 'agadir'),
  ('Agafay', 45, 'agafay', 'agafay'),
  ('Agdz (zagoura)', 45, 'agdz', 'agdz'),
  ('Aghbalou', 45, 'aghbalou', 'aghbalou'),
  ('Agouidir', 45, 'agouidir', 'agouidir'),
  ('Agouim', 45, 'agouim', 'agouim'),
  ('Agourai', 45, 'agourai', 'agourai'),
  ('Aguelmous', 39, 'aguelmous', 'aguelmous'),
  ('Ahejarr Ennehal', 45, 'ahejarr ennehal', 'ahejarr ennehal'),
  ('Ahfir', 45, 'ahfir', 'ahfir'),
  ('Ain Aicha', 45, 'ain aicha', 'ain aicha'),
  ('Ain Attig', 39, 'ain attig', 'ain attig'),
  ('Ain chkaf', 39, 'ain chkaf', 'ain chkaf'),
  ('Ain El Aouda', 39, 'ain el aouda', 'ain el aouda'),
  ('Ain Harrouda', 29, 'ain harrouda', 'ain harrouda'),
  ('Ain Lahcen', 45, 'ain lahcen', 'ain lahcen'),
  ('Ain Leuh', 45, 'ain leuh', 'ain leuh'),
  ('Ain Mediouna', 45, 'ain mediouna', 'ain mediouna'),
  ('Ain Taoujdate', 45, 'ain taoujdate', 'ain taoujdate'),
  ('Ain-Cheggag', 45, 'ain cheggag', 'ain cheggag'),
  ('Ait Aiaaza', 45, 'ait aiaaza', 'ait aiaaza'),
  ('Ait Aissa Ou Brahim', 45, 'ait aissa ou brahim', 'ait aissa ou brahim'),
  ('Ait Amira', 39, 'ait amira', 'ait amira'),
  ('Ait Boudaoud', 45, 'ait boudaoud', 'ait boudaoud'),
  ('Ait Daoud', 45, 'ait daoud', 'ait daoud'),
  ('Ait hadi', 45, 'ait hadi', 'ait hadi'),
  ('Ait ourir', 45, 'ait ourir', 'ait ourir'),
  ('Ait Sedrate Sahl Gharbia', 45, 'ait sedrate sahl gharbia', 'ait sedrate sahl gharbia'),
  ('Ait-Kamara', 45, 'ait kamara', 'ait kamara'),
  ('Ajdir ( al hoceima )', 45, 'ajdir', 'ajdir'),
  ('Aklim', 45, 'aklim', 'aklim'),
  ('Aknoul', 39, 'aknoul', 'aknoul'),
  ('Al Aaroui', 45, 'al aaroui', 'al aaroui'),
  ('Al Hoceima', 39, 'al hoceima', 'al hoceima'),
  ('Alnif', 45, 'alnif', 'alnif'),
  ('Alouidane', 45, 'alouidane', 'alouidane'),
  ('Amerzgane', 45, 'amerzgane', 'amerzgane'),
  ('Anza', 39, 'anza', 'anza'),
  ('Anzal', 45, 'anzal', 'anzal'),
  ('Aoufous', 45, 'aoufous', 'aoufous'),
  ('Aoulouz', 45, 'aoulouz', 'aoulouz'),
  ('Aourir \"Région Agadir\"', 39, 'aourir region agadir', 'aourir'),
  ('Aquermoud', 45, 'aquermoud', 'aquermoud'),
  ('Arfoud', 45, 'arfoud', 'arfoud'),
  ('Asni', 45, 'asni', 'asni'),
  ('Assa', 45, 'assa', 'assa'),
  ('Assahrij', 45, 'assahrij', 'assahrij'),
  ('Assilah', 39, 'assilah', 'assilah'),
  ('Ayt Ihya', 45, 'ayt ihya', 'ayt ihya'),
  ('Azemmour', 39, 'azemmour', 'azemmour'),
  ('Azilal', 45, 'azilal', 'azilal'),
  ('Azla', 45, 'azla', 'azla'),
  ('Azrou \"Région d''Agadir\"', 45, 'azrou region d agadir', 'azrou'),
  ('Azrou \"Région de Fès-Meknès\"', 45, 'azrou region de fes meknes', 'azrou'),
  ('Aïn Erreggada', 45, 'ain erreggada', 'ain erreggada'),
  ('Aïn-Béni-Mathar', 45, 'ain beni mathar', 'ain beni mathar'),
  ('Aït Ben Haddou', 45, 'ait ben haddou', 'ait ben haddou'),
  ('Aït Ishaq', 39, 'ait ishaq', 'ait ishaq'),
  ('Aït Melloul', 35, 'ait melloul', 'ait melloul'),
  ('Aït Tarzout', 45, 'ait tarzout', 'ait tarzout'),
  ('Bab Berred', 39, 'bab berred', 'bab berred'),
  ('Bab Marzouka', 45, 'bab marzouka', 'bab marzouka'),
  ('Bab Taza', 45, 'bab taza', 'bab taza'),
  ('Bani Walid', 45, 'bani walid', 'bani walid'),
  ('Bassatine El Menzeh', 39, 'bassatine el menzeh', 'bassatine el menzeh'),
  ('Bejaad', 39, 'bejaad', 'bejaad'),
  ('Belaaguid', 45, 'belaaguid', 'belaaguid'),
  ('Belfaa', 45, 'belfaa', 'belfaa'),
  ('Belyounech', 45, 'belyounech', 'belyounech'),
  ('Ben Ahmed', 39, 'ben ahmed', 'ben ahmed'),
  ('Ben Karrich', 45, 'ben karrich', 'ben karrich'),
  ('Ben Rahmoun', 45, 'ben rahmoun', 'ben rahmoun'),
  ('Ben Taieb', 45, 'ben taieb', 'ben taieb'),
  ('Benguerir', 39, 'benguerir', 'benguerir'),
  ('Beni Ayat', 39, 'beni ayat', 'beni ayat'),
  ('Beni Chiker', 45, 'beni chiker', 'beni chiker'),
  ('Beni Drar', 45, 'beni drar', 'beni drar'),
  ('Beni Ensar', 39, 'beni ensar', 'beni ensar'),
  ('Beni Hassane', 45, 'beni hassane', 'beni hassane'),
  ('Beni Mellal', 35, 'beni mellal', 'beni mellal'),
  ('Beni Sidal Jbel', 45, 'beni sidal jbel', 'beni sidal jbel'),
  ('Beni zoli', 45, 'beni zoli', 'beni zoli'),
  ('Benslimane', 35, 'benslimane', 'benslimane'),
  ('Berkane', 39, 'berkane', 'berkane'),
  ('Berrechid', 35, 'berrechid', 'berrechid'),
  ('Biougra', 39, 'biougra', 'biougra'),
  ('Bir Jdid', 45, 'bir jdid', 'bir jdid'),
  ('Birkouate', 45, 'birkouate', 'birkouate'),
  ('Bleida', 45, 'bleida', 'bleida'),
  ('Bni Ahmed Cherqia', 45, 'bni ahmed cherqia', 'bni ahmed cherqia'),
  ('Bni Bouayach', 45, 'bni bouayach', 'bni bouayach'),
  ('Bni Boufrah', 45, 'bni boufrah', 'bni boufrah'),
  ('Bni Hadifa', 45, 'bni hadifa', 'bni hadifa'),
  ('Bni yakhlef', 35, 'bni yakhlef', 'bni yakhlef'),
  ('Bouaboud', 45, 'bouaboud', 'bouaboud'),
  ('Bouarg', 39, 'bouarg', 'bouarg'),
  ('Boudenib', 45, 'boudenib', 'boudenib'),
  ('Bouderbala', 45, 'bouderbala', 'bouderbala'),
  ('Boudinar', 45, 'boudinar', 'boudinar'),
  ('Boufakrane', 45, 'boufakrane', 'boufakrane'),
  ('Boughriba', 45, 'boughriba', 'boughriba'),
  ('Bouhouda', 45, 'bouhouda', 'bouhouda'),
  ('Boujdour', 45, 'boujdour', 'boujdour'),
  ('Boujniba', 39, 'boujniba', 'boujniba'),
  ('Boukidaren', 45, 'boukidaren', 'boukidaren'),
  ('Boulman', 45, 'boulman', 'boulman'),
  ('Boumalen dades', 45, 'boumalen dades', 'boumalen dades'),
  ('Boumia', 45, 'boumia', 'boumia'),
  ('Bounoir', 39, 'bounoir', 'bounoir'),
  ('Boured', 45, 'boured', 'boured'),
  ('Bouskoura-Centre', 29, 'bouskoura centre', 'bouskoura centre'),
  ('Bouskoura-Ouled Saleh', 29, 'bouskoura ouled saleh', 'bouskoura ouled saleh'),
  ('Bouskoura-Ville Verte', 29, 'bouskoura ville verte', 'bouskoura ville verte'),
  ('Bouznika', 35, 'bouznika', 'bouznika'),
  ('Bouârfa', 45, 'bouarfa', 'bouarfa'),
  ('Bradia', 39, 'bradia', 'bradia'),
  ('Cabo Negro', 39, 'cabo negro', 'cabo negro'),
  ('Casablanca', 19, 'casablanca', 'casablanca'),
  ('Chefchaouen', 39, 'chefchaouen', 'chefchaouen'),
  ('Chellalat Mohammedia', 35, 'chellalat mohammedia', 'chellalat mohammedia'),
  ('Chichaoua', 39, 'chichaoua', 'chichaoua'),
  ('Chrifia', 45, 'chrifia', 'chrifia'),
  ('Chtouka - région Agadir', 39, 'chtouka region agadir', 'chtouka'),
  ('Chwiter', 45, 'chwiter', 'chwiter'),
  ('Dakhla', 39, 'dakhla', 'dakhla'),
  ('Dar Bouaza', 29, 'dar bouaza', 'dar bouaza'),
  ('Dar Essalam', 39, 'dar essalam', 'dar essalam'),
  ('Dar Ould Zidouh', 39, 'dar ould zidouh', 'dar ould zidouh'),
  ('Dar-El Kebdani', 45, 'dar el kebdani', 'dar el kebdani'),
  ('Dcheira El Jihadia', 39, 'dcheira el jihadia', 'dcheira el jihadia'),
  ('Demnate', 45, 'demnate', 'demnate'),
  ('Deroua', 29, 'deroua', 'deroua'),
  ('Dlalha', 45, 'dlalha', 'dlalha'),
  ('Douar laarab ( essaouira )', 45, 'douar laarab', 'douar laarab'),
  ('Douar Lahna', 39, 'douar lahna', 'douar lahna'),
  ('Drarga', 39, 'drarga', 'drarga'),
  ('Driouch', 45, 'driouch', 'driouch'),
  ('Echemmaia', 39, 'echemmaia', 'echemmaia'),
  ('El Aarjate', 45, 'el aarjate', 'el aarjate'),
  ('El Aïoun Charqiya', 45, 'el aioun charqiya', 'el aioun charqiya'),
  ('El Borouj \"Région de Settat\"', 45, 'el borouj region de settat', 'el borouj'),
  ('El Gara', 39, 'el gara', 'el gara'),
  ('El Hajeb', 45, 'el hajeb', 'el hajeb'),
  ('El Haouzia ( el jadida )', 45, 'el haouzia', 'el haouzia'),
  ('El jadida', 35, 'el jadida', 'el jadida'),
  ('El Jebeha', 45, 'el jebeha', 'el jebeha'),
  ('El Kebab', 45, 'el kebab', 'el kebab'),
  ('El Kelaa Des Sraghna', 39, 'el kelaa des sraghna', 'el kelaa des sraghna'),
  ('El Ksiba', 45, 'el ksiba', 'el ksiba'),
  ('El Mansouria', 35, 'el mansouria', 'el mansouria'),
  ('El-afak', 39, 'el afak', 'el afak'),
  ('Er-Rich', 45, 'er rich', 'er rich'),
  ('Errachidia', 45, 'errachidia', 'errachidia'),
  ('Errahma', 29, 'errahma', 'errahma'),
  ('Errouha', 45, 'errouha', 'errouha'),
  ('Essaouira', 35, 'essaouira', 'essaouira'),
  ('Essemara', 45, 'essemara', 'essemara'),
  ('farkhana', 45, 'farkhana', 'farkhana'),
  ('Fes', 35, 'fes', 'fes'),
  ('Fezouata', 45, 'fezouata', 'fezouata'),
  ('Figuig', 45, 'figuig', 'figuig'),
  ('Fnideq', 39, 'fnideq', 'fnideq'),
  ('Foum Oudi', 39, 'foum oudi', 'foum oudi'),
  ('Fquih Ben Salah', 45, 'fquih ben salah', 'fquih ben salah'),
  ('Fricha', 45, 'fricha', 'fricha'),
  ('Galaz', 45, 'galaz', 'galaz'),
  ('Ghafsai', 45, 'ghafsai', 'ghafsai'),
  ('Ghazoua', 39, 'ghazoua', 'ghazoua'),
  ('Goulmima', 45, 'goulmima', 'goulmima'),
  ('Guelmim', 39, 'guelmim', 'guelmim'),
  ('Guercif', 39, 'guercif', 'guercif'),
  ('Gueznaia', 45, 'gueznaia', 'gueznaia'),
  ('Guigou', 45, 'guigou', 'guigou'),
  ('Guisser', 45, 'guisser', 'guisser'),
  ('Had Boumoussa', 39, 'had boumoussa', 'had boumoussa'),
  ('Had Draa', 45, 'had draa', 'had draa'),
  ('Had Soualem', 35, 'had soualem', 'had soualem'),
  ('Haj Kaddour', 45, 'haj kaddour', 'haj kaddour'),
  ('Hajria Ouled Daoud', 45, 'hajria ouled daoud', 'hajria ouled daoud'),
  ('Harbile', 39, 'harbile', 'harbile'),
  ('Harhoura', 39, 'harhoura', 'harhoura'),
  ('Hettan', 39, 'hettan', 'hettan'),
  ('Ifran', 45, 'ifran', 'ifran'),
  ('Ighoud', 45, 'ighoud', 'ighoud'),
  ('Ighrem Laâlam', 39, 'ighrem laalam', 'ighrem laalam'),
  ('Ighrem N''ougdal', 45, 'ighrem n', 'ighrem n'),
  ('Imi Ouaddar', 45, 'imi ouaddar', 'imi ouaddar'),
  ('Imintanout', 45, 'imintanout', 'imintanout'),
  ('Imouzzer du Kandar', 45, 'imouzzer du kandar', 'imouzzer du kandar'),
  ('Imzouren', 45, 'imzouren', 'imzouren'),
  ('Inzegane', 35, 'inzegane', 'inzegane'),
  ('Issaguen', 45, 'issaguen', 'issaguen'),
  ('Itzer', 45, 'itzer', 'itzer'),
  ('Jaadar', 39, 'jaadar', 'jaadar'),
  ('Jamaat Shaim', 45, 'jamaat shaim', 'jamaat shaim'),
  ('Jebila', 45, 'jebila', 'jebila'),
  ('Jerada', 45, 'jerada', 'jerada'),
  ('Jorf ( errachidia )', 45, 'jorf', 'jorf'),
  ('Jorf El Melha', 45, 'jorf el melha', 'jorf el melha'),
  ('KAA ASRASS', 45, 'kaa asrass', 'kaa asrass'),
  ('Kariat Arekmane', 45, 'kariat arekmane', 'kariat arekmane'),
  ('Kariat Ba Mohamed', 45, 'kariat ba mohamed', 'kariat ba mohamed'),
  ('Kasba Tadla', 39, 'kasba tadla', 'kasba tadla'),
  ('Kassita', 45, 'kassita', 'kassita'),
  ('Kelaat M''Gouna', 45, 'kelaat m', 'kelaat m'),
  ('Kenitra', 35, 'kenitra', 'kenitra'),
  ('Khandagour', 45, 'khandagour', 'khandagour'),
  ('Khemis Des Zemamra', 39, 'khemis des zemamra', 'khemis des zemamra'),
  ('Khemis du Sahel', 45, 'khemis du sahel', 'khemis du sahel'),
  ('Khemisset', 39, 'khemisset', 'khemisset'),
  ('Khenichet', 45, 'khenichet', 'khenichet'),
  ('Khenifra', 39, 'khenifra', 'khenifra'),
  ('Khlalfa', 45, 'khlalfa', 'khlalfa'),
  ('Khouribga', 35, 'khouribga', 'khouribga'),
  ('Ksar El Kebir', 39, 'ksar el kebir', 'ksar el kebir'),
  ('Ksar Sghir', 45, 'ksar sghir', 'ksar sghir'),
  ('Laaouamera', 45, 'laaouamera', 'laaouamera'),
  ('Laarache', 39, 'laarache', 'laarache'),
  ('Laattaouia', 39, 'laattaouia', 'laattaouia'),
  ('Laayayta', 39, 'laayayta', 'laayayta'),
  ('Lagfifat', 45, 'lagfifat', 'lagfifat'),
  ('Lahbichat', 45, 'lahbichat', 'lahbichat'),
  ('Lalla Mimouna', 45, 'lalla mimouna', 'lalla mimouna'),
  ('Laâyoune', 39, 'laayoune', 'laayoune'),
  ('Leqliaa', 39, 'leqliaa', 'leqliaa'),
  ('Loudaya', 39, 'loudaya', 'loudaya'),
  ('Loulad', 45, 'loulad', 'loulad'),
  ('M''Hamid El Ghizlane', 45, 'm', 'm'),
  ('M''haya', 45, 'm', 'm'),
  ('Madagh', 39, 'madagh', 'madagh'),
  ('Mariouari', 45, 'mariouari', 'mariouari'),
  ('Marnissa', 45, 'marnissa', 'marnissa'),
  ('Marrakech', 35, 'marrakech', 'marrakech'),
  ('Martil', 39, 'martil', 'martil'),
  ('Massa', 45, 'massa', 'massa'),
  ('Mdiq', 39, 'mdiq', 'mdiq'),
  ('Mechra Bel Ksiri', 45, 'mechra bel ksiri', 'mechra bel ksiri'),
  ('Mediouna', 29, 'mediouna', 'mediouna'),
  ('Mehdia', 39, 'mehdia', 'mehdia'),
  ('Mejat \"Région de Fès-Meknès\"', 45, 'mejat region de fes meknes', 'mejat'),
  ('Mejjat - Région de Marrakech', 45, 'mejjat region de marrakech', 'mejjat'),
  ('Meknes', 35, 'meknes', 'meknes'),
  ('Melloussa', 45, 'melloussa', 'melloussa'),
  ('Mers El Kheir', 39, 'mers el kheir', 'mers el kheir'),
  ('Merzouga', 45, 'merzouga', 'merzouga'),
  ('Meskala', 45, 'meskala', 'meskala'),
  ('Messawerr Rasso', 45, 'messawerr rasso', 'messawerr rasso'),
  ('Midar', 45, 'midar', 'midar'),
  ('Midelt', 45, 'midelt', 'midelt'),
  ('Mirleft', 45, 'mirleft', 'mirleft'),
  ('Missour', 45, 'missour', 'missour'),
  ('Mnar', 45, 'mnar', 'mnar'),
  ('Mohammedia', 29, 'mohammedia', 'mohammedia'),
  ('Mohammedia - Al Massira', 29, 'mohammedia al massira', 'mohammedia al massira'),
  ('Mohammedia - Al Wahda', 29, 'mohammedia al wahda', 'mohammedia al wahda'),
  ('Mohammedia - Alia', 29, 'mohammedia alia', 'mohammedia alia'),
  ('Mohammedia - Hassania', 29, 'mohammedia hassania', 'mohammedia hassania'),
  ('Mohammedia - Hay Wafa', 29, 'mohammedia hay wafa', 'mohammedia hay wafa'),
  ('Mohammedia - Kasbah', 29, 'mohammedia kasbah', 'mohammedia kasbah'),
  ('Mohammedia - Nassim', 29, 'mohammedia nassim', 'mohammedia nassim'),
  ('Mohammedia - Parc', 29, 'mohammedia parc', 'mohammedia parc'),
  ('Moulay Abdellah', 39, 'moulay abdellah', 'moulay abdellah'),
  ('Moulay Bousselham', 45, 'moulay bousselham', 'moulay bousselham'),
  ('Moulay Idriss zerhouni', 45, 'moulay idriss zerhouni', 'moulay idriss zerhouni'),
  ('Moulay Yâcoub', 39, 'moulay yacoub', 'moulay yacoub'),
  ('Mrirt', 39, 'mrirt', 'mrirt'),
  ('Msemrir', 45, 'msemrir', 'msemrir'),
  ('Mzoudia', 45, 'mzoudia', 'mzoudia'),
  ('Nador', 35, 'nador', 'nador'),
  ('Nkoub', 45, 'nkoub', 'nkoub'),
  ('Nouacer', 29, 'nouacer', 'nouacer'),
  ('Ouahat Sidi Brahim', 45, 'ouahat sidi brahim', 'ouahat sidi brahim'),
  ('Oualidia', 39, 'oualidia', 'oualidia'),
  ('Ouaouizeght', 39, 'ouaouizeght', 'ouaouizeght'),
  ('Ouarzazate', 39, 'ouarzazate', 'ouarzazate'),
  ('Ouazzane', 45, 'ouazzane', 'ouazzane'),
  ('Oued Amlil', 39, 'oued amlil', 'oued amlil'),
  ('Oued laou', 45, 'oued laou', 'oued laou'),
  ('Oued Zem', 39, 'oued zem', 'oued zem'),
  ('Ouislane', 45, 'ouislane', 'ouislane'),
  ('Oujda', 35, 'oujda', 'oujda'),
  ('Oulad Abbou', 45, 'oulad abbou', 'oulad abbou'),
  ('Oulad Ali', 39, 'oulad ali', 'oulad ali'),
  ('Oulad Amrane \"Région El Jadida\"', 45, 'oulad amrane region el jadida', 'oulad amrane'),
  ('Oulad Ayad', 39, 'oulad ayad', 'oulad ayad'),
  ('Oulad Azzouz Dar 16', 35, 'oulad azzouz dar 16', 'oulad azzouz dar 16'),
  ('Oulad Berhil', 45, 'oulad berhil', 'oulad berhil'),
  ('Oulad Frej', 45, 'oulad frej', 'oulad frej'),
  ('Oulad M''barek', 39, 'oulad m', 'oulad m'),
  ('Oulad Said \"Région de Settat\"', 45, 'oulad said region de settat', 'oulad said'),
  ('Oulad Tayeb', 39, 'oulad tayeb', 'oulad tayeb'),
  ('Oulad Teima', 39, 'oulad teima', 'oulad teima'),
  ('Oulad Yaich', 39, 'oulad yaich', 'oulad yaich'),
  ('Oulad Youssef', 39, 'oulad youssef', 'oulad youssef'),
  ('Oulad Zmam', 39, 'oulad zmam', 'oulad zmam'),
  ('Ouled Dahhou', 45, 'ouled dahhou', 'ouled dahhou'),
  ('Ouled Hassoune', 45, 'ouled hassoune', 'ouled hassoune'),
  ('Ouled Moumna', 45, 'ouled moumna', 'ouled moumna'),
  ('Ouled Settout', 45, 'ouled settout', 'ouled settout'),
  ('Oulmès', 45, 'oulmes', 'oulmes'),
  ('Ounagha', 45, 'ounagha', 'ounagha'),
  ('Ourika', 45, 'ourika', 'ourika'),
  ('Ourtzagh', 45, 'ourtzagh', 'ourtzagh'),
  ('Outat El Haj', 45, 'outat el haj', 'outat el haj'),
  ('Rabat', 35, 'rabat', 'rabat'),
  ('Ras El Ain \"Région de Settat\"', 45, 'ras el ain region de settat', 'ras el ain'),
  ('Ras El Ma - Cap de l''eau', 39, 'ras el ma cap de l', 'ras el ma cap de l'),
  ('Rencon', 39, 'rencon', 'rencon'),
  ('Rissani', 45, 'rissani', 'rissani'),
  ('Rommani', 39, 'rommani', 'rommani'),
  ('Safi', 35, 'safi', 'safi'),
  ('Saidia', 39, 'saidia', 'saidia'),
  ('Saiss', 39, 'saiss', 'saiss'),
  ('Sakia El hamra', 45, 'sakia el hamra', 'sakia el hamra'),
  ('Sala El Jadida', 39, 'sala el jadida', 'sala el jadida'),
  ('Sale', 35, 'sale', 'sale'),
  ('Sebt Ben Sassi', 45, 'sebt ben sassi', 'sebt ben sassi'),
  ('Sebt El Guerdane', 45, 'sebt el guerdane', 'sebt el guerdane'),
  ('Sebt Gzoula', 39, 'sebt gzoula', 'sebt gzoula'),
  ('Sebt Jahjouhe', 45, 'sebt jahjouhe', 'sebt jahjouhe'),
  ('Sebt Oulad Nemma', 45, 'sebt oulad nemma', 'sebt oulad nemma'),
  ('Sefrou', 45, 'sefrou', 'sefrou'),
  ('Selouane', 39, 'selouane', 'selouane'),
  ('Settat', 35, 'settat', 'settat'),
  ('Sid L''Mokhtar', 45, 'sid l', 'sid l'),
  ('Sidi Abdellah Ghiyat', 45, 'sidi abdellah ghiyat', 'sidi abdellah ghiyat'),
  ('Sidi Addi', 45, 'sidi addi', 'sidi addi'),
  ('Sidi Allal El Bahraoui', 45, 'sidi allal el bahraoui', 'sidi allal el bahraoui'),
  ('Sidi Allal Tazi', 45, 'sidi allal tazi', 'sidi allal tazi'),
  ('Sidi Aïssa', 39, 'sidi aissa', 'sidi aissa'),
  ('Sidi Bennour', 39, 'sidi bennour', 'sidi bennour'),
  ('Sidi Bibi', 45, 'sidi bibi', 'sidi bibi'),
  ('Sidi Bou Othmane', 45, 'sidi bou othmane', 'sidi bou othmane'),
  ('Sidi bou zid Chichaoua', 45, 'sidi bou zid chichaoua', 'sidi bou zid chichaoua'),
  ('Sidi Bouknadel', 39, 'sidi bouknadel', 'sidi bouknadel'),
  ('Sidi Bouzid ( el jadida )', 39, 'sidi bouzid', 'sidi bouzid'),
  ('Sidi Bouzid ( safi )', 35, 'sidi bouzid', 'sidi bouzid'),
  ('Sidi chiker', 45, 'sidi chiker', 'sidi chiker'),
  ('Sidi El Ayedi', 45, 'sidi el ayedi', 'sidi el ayedi'),
  ('Sidi Hajjaj \"Région de Settat\"', 45, 'sidi hajjaj region de settat', 'sidi hajjaj'),
  ('Sidi Hrazem', 39, 'sidi hrazem', 'sidi hrazem'),
  ('Sidi Hssain', 45, 'sidi hssain', 'sidi hssain'),
  ('Sidi Ifni', 45, 'sidi ifni', 'sidi ifni'),
  ('Sidi Jaber', 39, 'sidi jaber', 'sidi jaber'),
  ('Sidi Kacem', 45, 'sidi kacem', 'sidi kacem'),
  ('Sidi Kaouki', 45, 'sidi kaouki', 'sidi kaouki'),
  ('Sidi Moussa \"Région de Marrakech\"', 45, 'sidi moussa region de marrakech', 'sidi moussa'),
  ('Sidi rahal', 35, 'sidi rahal', 'sidi rahal'),
  ('Sidi Slimane', 45, 'sidi slimane', 'sidi slimane'),
  ('Sidi Smaïl', 45, 'sidi smail', 'sidi smail'),
  ('Sidi Taibi', 45, 'sidi taibi', 'sidi taibi'),
  ('Sidi Yahya El Gharb', 45, 'sidi yahya el gharb', 'sidi yahya el gharb'),
  ('Sidi Zouine', 45, 'sidi zouine', 'sidi zouine'),
  ('Skhinate', 45, 'skhinate', 'skhinate'),
  ('Skhirat', 39, 'skhirat', 'skhirat'),
  ('Skhour Rehamna', 39, 'skhour rehamna', 'skhour rehamna'),
  ('Skoura', 45, 'skoura', 'skoura'),
  ('Smimou', 45, 'smimou', 'smimou'),
  ('Souihla', 45, 'souihla', 'souihla'),
  ('Souira Guedima', 39, 'souira guedima', 'souira guedima'),
  ('Souk El Arbaa Du Gharb', 45, 'souk el arbaa du gharb', 'souk el arbaa du gharb'),
  ('Souk Sebt', 39, 'souk sebt', 'souk sebt'),
  ('Stehat', 45, 'stehat', 'stehat'),
  ('Tabounte Ouarzazate', 45, 'tabounte ouarzazate', 'tabounte ouarzazate'),
  ('Tabourahte', 45, 'tabourahte', 'tabourahte'),
  ('Tafersit', 45, 'tafersit', 'tafersit'),
  ('Tafetachte', 45, 'tafetachte', 'tafetachte'),
  ('Taghazout', 45, 'taghazout', 'taghazout'),
  ('Taghbalt', 45, 'taghbalt', 'taghbalt'),
  ('Tagounite', 45, 'tagounite', 'tagounite'),
  ('Tagzirt', 39, 'tagzirt', 'tagzirt'),
  ('Tahanaout', 39, 'tahanaout', 'tahanaout'),
  ('Tahla', 45, 'tahla', 'tahla'),
  ('Taliouine', 45, 'taliouine', 'taliouine'),
  ('Talmest', 45, 'talmest', 'talmest'),
  ('Tamanar', 45, 'tamanar', 'tamanar'),
  ('Tamansourt', 39, 'tamansourt', 'tamansourt'),
  ('Tamaris', 29, 'tamaris', 'tamaris'),
  ('Tamegroute', 45, 'tamegroute', 'tamegroute'),
  ('Tamellalt', 39, 'tamellalt', 'tamellalt'),
  ('Tameslouht', 45, 'tameslouht', 'tameslouht'),
  ('Tamesna', 39, 'tamesna', 'tamesna'),
  ('Tamezmoute', 45, 'tamezmoute', 'tamezmoute'),
  ('Tamraght', 45, 'tamraght', 'tamraght'),
  ('Tamsamane', 45, 'tamsamane', 'tamsamane'),
  ('Tan-Tan', 45, 'tan tan', 'tan tan'),
  ('Tanger', 35, 'tanger', 'tanger'),
  ('Tansifte', 45, 'tansifte', 'tansifte'),
  ('Taounate', 39, 'taounate', 'taounate'),
  ('Taourirt', 45, 'taourirt', 'taourirt'),
  ('Tarast', 39, 'tarast', 'tarast'),
  ('Targuist', 45, 'targuist', 'targuist'),
  ('Taroudant', 39, 'taroudant', 'taroudant'),
  ('Tata', 45, 'tata', 'tata'),
  ('Taza', 39, 'taza', 'taza'),
  ('Tazarine', 45, 'tazarine', 'tazarine'),
  ('Taznakht', 45, 'taznakht', 'taznakht'),
  ('Telat Azlaf', 45, 'telat azlaf', 'telat azlaf'),
  ('Temara', 35, 'temara', 'temara'),
  ('Temsia', 39, 'temsia', 'temsia'),
  ('Tendrara', 45, 'tendrara', 'tendrara'),
  ('Ternata', 45, 'ternata', 'ternata'),
  ('Tetouan', 39, 'tetouan', 'tetouan'),
  ('Tiddas', 45, 'tiddas', 'tiddas'),
  ('Tidzi', 45, 'tidzi', 'tidzi'),
  ('Tiflet', 39, 'tiflet', 'tiflet'),
  ('Tighassaline', 39, 'tighassaline', 'tighassaline'),
  ('Tikiwin', 35, 'tikiwin', 'tikiwin'),
  ('Timahdite', 45, 'timahdite', 'timahdite'),
  ('Timedline', 45, 'timedline', 'timedline'),
  ('Timezgadiouine', 45, 'timezgadiouine', 'timezgadiouine'),
  ('Timoulilt', 39, 'timoulilt', 'timoulilt'),
  ('Tinejdad', 45, 'tinejdad', 'tinejdad'),
  ('Tinghir', 45, 'tinghir', 'tinghir'),
  ('Tinzouline', 45, 'tinzouline', 'tinzouline'),
  ('Tissa', 45, 'tissa', 'tissa'),
  ('Tit Melil', 29, 'tit melil', 'tit melil'),
  ('Tizi Ouasli', 45, 'tizi ouasli', 'tizi ouasli'),
  ('Tiznit', 39, 'tiznit', 'tiznit'),
  ('Tiztoutine', 45, 'tiztoutine', 'tiztoutine'),
  ('Tlat Bouguedra', 39, 'tlat bouguedra', 'tlat bouguedra'),
  ('Tleta-El Henchane', 45, 'tleta el henchane', 'tleta el henchane'),
  ('Touima', 45, 'touima', 'touima'),
  ('Tssoultante', 39, 'tssoultante', 'tssoultante'),
  ('Youssoufia', 39, 'youssoufia', 'youssoufia'),
  ('zaer', 35, 'zaer', 'zaer'),
  ('Zagoura', 45, 'zagoura', 'zagoura'),
  ('Zaida', 45, 'zaida', 'zaida'),
  ('Zaio', 45, 'zaio', 'zaio'),
  ('Zaouiat Cheikh', 39, 'zaouiat cheikh', 'zaouiat cheikh'),
  ('Zeghanghane', 39, 'zeghanghane', 'zeghanghane'),
  ('Zouada', 45, 'zouada', 'zouada');

-- Mirrors src/lib/shipping.ts's normalize(): strip accents, lowercase,
-- drop parenthetical qualifiers, drop a trailing quoted region label,
-- collapse remaining punctuation/whitespace to single spaces, trim.
CREATE OR REPLACE FUNCTION public._shipping_normalize(raw text)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT trim(
    regexp_replace(
      regexp_replace(
        regexp_replace(lower(extensions.unaccent(coalesce(raw, ''))), '\([^)]*\)', ' ', 'g'),
        '[''"’][^''"’]*$', ' ', 'g'
      ),
    '[^a-z0-9]+', ' ', 'g')
  )
$$;

-- Mirrors src/lib/shipping.ts's baseName(): the normalized name, truncated
-- at the first standalone occurrence of the word "region".
CREATE OR REPLACE FUNCTION public._shipping_base_name(raw text)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT trim(regexp_replace(public._shipping_normalize(raw), '\yregion\y.*$', ''))
$$;

-- Mirrors src/lib/shipping.ts's getShippingFee(): exact normalized match
-- first, then base-name match, then the standard default fee. "First
-- occurrence wins" ties are resolved the same way the frontend's Map does,
-- via id ASC (insertion order == the source rate sheet's order).
CREATE OR REPLACE FUNCTION public.get_shipping_fee(city_input text)
RETURNS numeric(10,2) LANGUAGE plpgsql STABLE AS $$
DECLARE
  full_norm text := public._shipping_normalize(city_input);
  base_norm text;
  matched_fee numeric(10,2);
BEGIN
  IF city_input IS NULL OR trim(city_input) = '' THEN
    RETURN 45; -- DEFAULT_SHIPPING_FEE, see src/data/shippingRates.ts
  END IF;

  SELECT fee INTO matched_fee FROM public.shipping_rates
  WHERE normalized_city = full_norm ORDER BY id ASC LIMIT 1;
  IF FOUND THEN RETURN matched_fee; END IF;

  base_norm := public._shipping_base_name(city_input);
  SELECT fee INTO matched_fee FROM public.shipping_rates
  WHERE base_city = base_norm ORDER BY id ASC LIMIT 1;
  IF FOUND THEN RETURN matched_fee; END IF;

  RETURN 45; -- DEFAULT_SHIPPING_FEE
END;
$$;

CREATE OR REPLACE FUNCTION public.set_order_shipping_fee()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.shipping_fee := public.get_shipping_fee(NEW.customer_city);
  RETURN NEW;
END;
$$;

CREATE TRIGGER orders_set_shipping_fee
  BEFORE INSERT ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.set_order_shipping_fee();
