// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Deliberately NOT persisted: this client is only used for admin login
    // (see Auth.tsx / Admin.tsx — the storefront has no customer accounts).
    // With persistSession/localStorage, a logged-in admin stays logged in
    // forever across restarts. We want the opposite: every fresh visit to
    // the admin area must re-authenticate.
    persistSession: false,
    autoRefreshToken: true,
  }
});