// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Session persisted to sessionStorage (not localStorage): the admin
    // stays logged in within the current tab — surviving iOS/iPadOS Safari
    // reloading the page in the background (e.g. after opening the native
    // photo picker), which previously wiped the in-memory-only session and
    // caused storage uploads to silently fall back to the anon key, tripping
    // the "row-level security policy" error on /admin.
    // Closing the tab/browser still clears it, so there's no indefinite
    // login like localStorage would give.
    persistSession: true,
    storage: window.sessionStorage,
    autoRefreshToken: true,
  }
});
